system:
  profile: "Server_Rack_A"
  type: "Standard"   # 指定這是一台 PFR or Standard 機種
  connection:
    ip: "10.10.11.73"
    user: "admin"
    pass: "cmb9.cmb9"
    root_pass: "Qobmc.2401"

# PFR 設定 (不更新，只稽核)
pfr:
  check_health: true

# 需要更新的元件清單
updates:

  - name: "MB_CPLD"
    type: "CPLD"
    subtype: "MB"  # 對應原本 device_map.py 的 key
    version: "01.04.00"
    file: "./img/CPLD/MB/S7Q_MB_01.04.00.tar.gz"

  # - name: "MB_CPLD"
  #   type: "CPLD"
  #   subtype: "MB"  # 對應原本 device_map.py 的 key
  #   version: "01.06.00"
  #   file: "./img/CPLD/MB/S7Q_MB_01.06.00.tar.gz"

  # - name: "SCM_CPLD"
  #   type: "CPLD"
  #   subtype: "SCM"  # 對應原本 device_map.py 的 key
  #   version: "01.00.00.01"
  #   file: "./img/CPLD/SCM/S7Q_GNR_SCM_01.00.00.01.tar.gz"

  # - name: "SCM_CPLD"
  #   type: "CPLD"
  #   subtype: "SCM"  # 對應原本 device_map.py 的 key
  #   version: "01.01.00"
  #   file: "./img/CPLD/SCM/S7Q_GNR_SCM_01.01.00.tar.gz"

  # - name: "System_BIOS"
  #   type: "BIOS"
  #   version: "3A18.QCT402_T"
  #   file: "./img/BIOS/3A18.QCT402_T.tar.gz"
  
  - name: "System_BIOS"
    type: "BIOS"
    version: "3A19.QCT101_T"
    file: "./img/BIOS/3A19.QCT101_T.tar.gz"

  # - name: "Server_BMC"
  #   type: "BMC"
  #   version: "3.24.00"
  #   file: "./img/BMC/quanta-s7q-20251128073847.tar"
  #   apply_time: "Immediate"  # Immediate or OnReset
  #   preserve: true          # preserve settings or not (like Factory Reset update)

  - name: "Server_BMC"
    type: "BMC"
    version: "3.25.00"
    file: "./img/BMC/quanta-s7q-20251218084518.tar"
    apply_time: "Immediate"  # Immediate or OnReset
    preserve: true          # preserve settings or not (like Factory Reset update)

  # - name: "Server_BMC"
  #   type: "BMC"
  #   version: "3.25.00"
  #   file: "./img/BMC/quanta-s7q-20251218084518.tar"
  #   apply_time: "Immediate"  # Immediate or OnReset
  #   preserve: false          # preserve settings or not (like Factory Reset update)

  # - name: "Server_BMC"
  #   type: "BMC"
  #   version: "3.25.00"
  #   file: "./img/BMC/pfr_3.25/bmc_cap_signed.bin"

  # - name: "Server_BMC"
  #   type: "BMC"
  #   version: "3.23.00"
  #   file: "./img/BMC/pfr_3.23/bmc_cap_signed.bin"
