system:
  profile: "Server_Rack_A"
  type: "Standard"   # 指定這是一台 PFR or Standard 機種
  connection:
    ip: "10.10.11.73"
    user: "admin"
    pass: "cmb9.cmb9"
    root_pass: "Qobmc.2401"

# PFR 設定 (不更新，只稽核)
pfr:
  check_health: true

# 需要更新的元件清單
updates:

  # - name: "MB_CPLD"
  #   type: "CPLD"
  #   version: "01.04.00"
  #   file: "./img/CPLD/MB/S7Q_MB_01.04.00.tar.gz"
  #   profile: "cpld_mb"

  # - name: "MB_CPLD"
  #   type: "CPLD"
  #   version: "01.06.00"
  #   file: "./img/CPLD/MB/S7Q_MB_01.06.00.tar.gz"
  #   profile: "cpld_mb"

  # - name: "SCM_CPLD"
  #   type: "CPLD"
  #   version: "01.00.00.01"
  #   file: "./img/CPLD/SCM/S7Q_GNR_SCM_01.00.00.01.tar.gz"
  #   profile: "cpld_scm"

  # - name: "SCM_CPLD"
  #   type: "CPLD"
  #   version: "01.01.00"
  #   file: "./img/CPLD/SCM/S7Q_GNR_SCM_01.01.00.tar.gz"
  #   profile: "cpld_scm"

  - name: "System_BIOS"
    type: "BIOS"
    version: "3A18.QCT402_T"
    file: "./img/BIOS/3A18.QCT402_T.tar.gz"
    profile: "standard_bios"
  
  # - name: "System_BIOS"
  #   type: "BIOS"
  #   version: "3A19.QCT101_T"
  #   file: "./img/BIOS/3A19.QCT101_T.tar.gz"
  #   profile: "standard_bios"

  # - name: "Server_BMC"
  #   type: "BMC"
  #   version: "3.24.00"
  #   file: "./img/BMC/quanta-s7q-20251128073847.tar"
  #   profile: "standard_bmc_dual"

  # - name: "Server_BMC"
  #   type: "BMC"
  #   version: "3.25.00"
  #   file: "./img/BMC/quanta-s7q-20251218084518.tar"
  #   profile: "standard_bmc"

# == Update Flow Control ==

  # - name: "BMC_Downgrade_Old"
  #   type: "BMC"
  #   version: "3.24.00"
  #   file: "./img/BMC/quanta-s7q-20251128073847.tar"
  #   profile: "standard_bmc_dual"

  # - name: "BMC_Upgrade_New"
  #   type: "BMC"
  #   version: "3.25.00"
  #   file: "./img/BMC/quanta-s7q-20251218084518.tar"
  #   profile: "standard_bmc_dual"

  # - name: "BMC_Reflash_New"
  #   type: "BMC"
  #   version: "3.25.00"
  #   file: "./img/BMC/quanta-s7q-20251218084518.tar"
  #   profile: "standard_bmc_dual"

  # - name: "MB_CPLD"
  #   type: "CPLD"
  #   version: "01.06.00"
  #   file: "./img/CPLD/MB/S7Q_MB_01.06.00.tar.gz"
  #   profile: "cpld_mb"

  # - name: "SCM_CPLD"
  #   type: "CPLD"
  #   version: "01.00.00.01"
  #   file: "./img/CPLD/SCM/S7Q_GNR_SCM_01.00.00.01.tar.gz"
  #   profile: "cpld_scm"

  # - name: "System_BIOS"
  #   type: "BIOS"
  #   version: "3A19.QCT101_T"
  #   file: "./img/BIOS/3A19.QCT101_T.tar.gz"
  #   profile: "standard_bios"

  # - name: "Server_BMC"
  #   type: "BMC"
  #   version: "3.25.00"
  #   file: "./img/BMC/quanta-s7q-20251218084518.tar"
  #   profile: "bmc_default"